### ISSUE TITLE
Gradle: Comparison to Maven

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/guide-gradle-intro#11]
Both the 'Building a web application with Gradle' and 'Building a web application with Maven' guides mention the benefits of using each technology in their respective guides within the 'What you’ll learn' section, though they seem to say roughly the same benefits. For example:

**Taken from the 'Building a web application with Gradle' guide:**
> One benefit of using a build tool like Gradle is that after you define the details of the project and any dependencies it has, Gradle automatically downloads and installs the dependencies.

**Taken from the 'Building a web application with Maven' guide:**
> One benefit of using Maven is that, once you have defined the details of the project and any dependencies it has, Maven automatically handles downloading and installing any and all of the dependencies.

Both of these guides seem to complete the same end-goal (albeit using different technologies). 
It may be helpful to include a comparison to **contrast both technologies**, giving different use case scenarios for each technology. E.g. Maven uses XML, Gradle uses Groovy, differences in performance, etc.

**Comment by AustinSeto** [comment]
Found connected issue in Maven guide: https://github.com/OpenLiberty/guide-maven-intro/issues/35
Unmerged PR in Maven guide: https://github.com/OpenLiberty/guide-maven-intro/pull/37

Will revisit adding this content to both this guide and the Maven guide.

**Comment by gkwan-ibm** [comment]
close for the [maven](https://openliberty.io/guides/maven-intro.html#what-youll-learn) and [gradle](https://openliberty.io/guides/gradle-intro.html#what-youll-learn) guides were updated
