### ISSUE TITLE
Guide doesn't work w/ Gradle v7 - needs LGP upgrade

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/guide-gradle-intro#114]
With Gradle v7.3.3, I get this on `gradle assemble`:

> * What went wrong:
> A problem occurred evaluating root project 'GradleSample'.
> > Failed to apply plugin 'liberty'.
>    > Could not create task ':compileJSP'.
>       > Could not create task of type 'CompileJSPTask'.
>          > Cannot set readonly property: level for class: org.gradle.internal.logging.services.DefaultLoggingManager
> 

Do we just want to update LGP to v3.3 or make a bigger deal about supporting Gradle v7?

**Comment by gkwan-ibm** [comment]
pending OpenLiberty/ci.gradle#655
need a new version 3.3.1+

**Comment by scottkurz** [comment]
> pending [OpenLiberty/ci.gradle#655](https://github.com/OpenLiberty/ci.gradle/issues/655) need a new version 3.3.1+

Hmm..it works for me, on Windows, with LGP v3.3 with Gradle 7.3.3..with Oracle Java 11 and OpenJDK J9 Java 11.
