### ISSUE TITLE
Prepare for Gradle 5.0

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-gradle-intro#17]
Some features in use by the guide are deprecated in Gradle 5.0.  Should review and update accordingly.

_Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0._

**Comment by yeekangc** [comment]
FYI, @mattbsox.

**Comment by gkwan-ibm** [comment]
refactored the guide to use gradlew and new liberty gradle plugin. @MaiHameed would you confirm whether the guide still use any deprecated features

**Comment by MaiHameed** [comment]
The `dev-mode` PR addressed this, the guide has been updated accordingly. Closing.
