### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-gradle-intro#30]
**Configure your project**
- [x] Guide says an empty `build.gradle` file is provided in the start directory, but then later in the section the user is instructed to create the `build.gradle` file. This is an inconsistency that should be addressed.
- [x] Guide says that you will build the `build.gradle` file piece-by-piece, but the user is then instructed to create the entire file. This inconsistency should also be addressed
- [x] "The first section of code defines the `war` `liberty` plug-ins that you want to use." -> `war` **and** `liberty` plug-ins
- [x] The `liberty` extension configures the Liberty server, which includes the following settings: -> `liberty` should be hotspotted
The `war` configuration names the WAR file GradleSample.war without a version in the name. -> Hotspot takes you to the `settings.gradle` file

**Testing your web application**
- [x] "The `test` section in your build file configures Gradle to run the integration tests in the */it/** folder." -> `test` hotspot is wrong, it should point to the testing section of the `build.gradle` file
- [x] "it is better to specify it in a single place like the Gradle `build.gradle` file, " -> `build.gradle` hotspot highlights entire file, doesn't just switch to it
- [x] "The `init()` method in the EndpointIT.java test class uses these system variables to build the URL of the application" -> `init()` hotspot is wrong and missing opening backtick on `EnpointIT.java`
- [x] Should we create the "src/test/java/io/openliberty/guides/hello/it" directory and add a `.gitkeep` instead of getting the user to create it?

**Nice work! Where to next?**
- [x] Should remove App Accelerator link since it is broken (see here for more details: https://github.com/OpenLiberty/guide-gradle-intro/issues/29)

**Comment by justineechen** [comment]
- Do we specifically ask the user to create the src/test/java/io/openliberty/guides/hello/it ? 
We definitely should have the path there already instead of asking users to create it. I will add the path, but did you see in the guide if it said to ask users to create the path? I can't find where it says that.

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-gradle-intro/commit/7b222313432ec4ebaf1bdcedeee62149965cd0ee

**Comment by andrewdes** [comment]
- [ ] "The `dependency directives` associate the war and java tasks to the liberty tasks to get proper task ordering." -> Hotspot highlights a blank line at the top

**Comment by andrewdes** [comment]
@justineechen the guide does not ask the user to create the `src/test/java/io/openliberty/guides/hello/it`, but the guide instructs them to create a file in that directory.
