### ISSUE TITLE
Show dependency inclusion of MicroProfile instead of only Servlet API 

### ISSUE THREAD

**Issue by julicjung** [OpenLiberty/guide-gradle-intro#47]
I suggest to enhance the build.gradle in the example with a more generally applicable dependencies; i.e. include something like:
`
providedCompile group: 'io.openliberty.features', name: 'features-bom', version: '19.0.0.5', ext: 'pom'
providedCompile group: 'io.openliberty.features', name: 'microProfile-2.2', version: '19.0.0.5'
`
This could also be just pointed out as a hint instead of being part of the standard flow in the guide.

The benefit would be that readers have an easier time starting out with a MicroProfile application instead of having just a Servlet example. At least for me it took some searching to put everything together and I felt the experience may be much more smooth.

**Comment by gkwan-ibm** [comment]
The guide was updated with the new version of Liberty Gradle Plugin. Now, the dependencies like following:
```
    providedCompile 'jakarta.platform:jakarta.jakartaee-api:8.0.0'
    providedCompile 'org.eclipse.microprofile:microprofile:3.2'
```

**Comment by yeekangc** [comment]
@julicjung, the dependencies aside, are you also suggesting that we should consider a different sample than the Servlet one?  Thank you.
