### ISSUE TITLE
Cannot run the server in DEBUG mode (gradle libertyDebug)

### ISSUE THREAD

**Issue by AndreiPadu** [OpenLiberty/guide-gradle-intro#53]
Recently, I have been trying to start the server in debug mode and it throws the following exception:

**Execution failed for task ':libertyDebug'.
> CWWKM2004E: When installDir is set, it must point to a directory that contains lib/ws-launch.jar.**

After several changes, it got me to the following:

**Execution failed for task ':libertyDebug'.

CWWKM2002E: Failed to invoke [.../build/wlp/bin/server, debug, sgd-serviceServer]. RC= 2 but expected=[0].**

Stacktrace does not show anything helpful either.

The sample provided does not work for me as well, nor other projects. Also, I could not find anything in the documentation to make it work.

TIA!

Note: I am using gradle 5.5.1 and liberty-gradle-plugin:2.6.5.

**Comment by yeekangc** [comment]
@AndreiPadu, can you please share your Gradle build script?

**Comment by AndreiPadu** [comment]
There's no need anymore. I figured it out. It seems that after every run of the server, I have to manually kill the process which keeps the 7777 port busy. Still, I am not sure if this is just a macOS problem.

**Comment by yeekangc** [comment]
Glad to hear that you figured it out, Andrei.

7777 is the default debug port.  Are you saying that the server wasn't cleanly stopped for you?

**Comment by AndreiPadu** [comment]
Yes, that’s right, the port was still busy.
