### ISSUE TITLE
Can't done this guide step

### ISSUE THREAD

**Issue by koshernoDev** [OpenLiberty/guide-gradle-intro#63]
Gradle build fails with an next error:

[ant:server] The command status:start failed because of a communication error with the server.
[ant:server] Server GradleSampleServer start failed. Check server logs for details.

> Task :libertyStart FAILED
:libertyStart (Thread[Execution worker for ':',5,main]) completed. Took 6.141 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libertyStart'.
> CWWKM2002E: Failed to invoke ["...\guide-gradle-intro\start\build\wlp\bin\server.bat", start, GradleSampleServer]. RC= 22 but expected=[0, 1].

I comment integrationTest.dependsOn 'libertyStart' build.gradle line. And build completes. But I see in the browser a failed test in EdpointIT testServlet. It says: java.net.ConnectException: Connection refused: connect.

PS: Got the same issue with the Maven in the next guide step

**Comment by MaiHameed** [comment]
Hello @koshernoDev I'd be happy to help figure out what isn't working for you. I tested the guide step by step process on my environment and I can't seem to reproduce the issue. Can you provide some more details to help me reproduce it? A few questions:

1. What OS are you running on? 
2. Do you have Gradle installed or are you using the Gradle wrapper?
3. Did you follow the guide step by step, by creating the necessary files in the `start/` directory?
4. If possible, can you provide the full log file for further investigation.

Much appreciated.

**Comment by MaiHameed** [comment]
In regards to the Maven issue, I assume you meant that you're facing a similar issue with our Maven guide? If that's the case, could you please open an issue in the guide's repo here: https://github.com/OpenLiberty/guide-maven-intro/issues so we can keep track, and I'll gladly help you out.

**Comment by MaiHameed** [comment]
Hello @koshernoDev, due to inactivity I'll be closing the issue, feel free to reopen if you're still experiencing a problem.
