### ISSUE TITLE
Grade build command fails on travis 

### ISSUE THREAD

**Issue by Ahmad-Ayyoub** [OpenLiberty/guide-gradle-intro#7]
From looking at travis log for gradle guide: https://travis-ci.org/OpenLiberty/guide-gradle-intro/builds/397883874 it seems to make sense that the gradle build will fail. This is because the gradle build is configured to report the tests summary through browsing the index.html file from the reports folder.

**Comment by Ahmad-Ayyoub** [comment]
It turns out that we can run a different gradle command like this: `gradle build -x openBrowser -x openTestReport -i`

**Comment by evelinec** [comment]
Issue resolved and tested.
