### ISSUE TITLE
Accessibility Verification Testing (AVT)

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-gradle-intro#74]
- [x] AVT 1 = Automated testing
  - use accessibility checker
  - https://github.com/OpenLiberty/guides-common/issues/486
- [x] AVT 2 = Manual testing
  - a picture requires alternative text to describe the image
  - table requires alternative text
  - test color contrast
  - test using keyboard instead of mouse
- [x] AVT 3 = Screen Reader testing
  - use JAWS screen reader

**Comment by DannyS03** [comment]
### AVT 1: Automated testing 
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/25497083/86961324-09303780-c12f-11ea-95dd-fb65027d13d4.png">

---

<img width="546" alt="image" src="https://user-images.githubusercontent.com/25497083/86961412-2d8c1400-c12f-11ea-8a1d-7e07179af163.png">

---



---

<img width="545" alt="image" src="https://user-images.githubusercontent.com/25497083/86961471-47c5f200-c12f-11ea-9643-9925d71d118e.png">

---

### AVT 2: Manual Testing

<img width="862" alt="image" src="https://user-images.githubusercontent.com/25497083/86961741-b86d0e80-c12f-11ea-8a39-a4f6caeba8c0.png">

---

<img width="874" alt="image" src="https://user-images.githubusercontent.com/25497083/86961764-c28f0d00-c12f-11ea-8dfe-15d86af43186.png">

---
