### ISSUE TITLE
Gradle: Update guide to use gradlew instead of manually-installed gradle

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/guide-gradle-intro#8]
According to the [Gradle guide](https://docs.gradle.org/current/userguide/gradle_wrapper.html), the "Gradle Wrapper" is the preferred way to use gradle.
> The recommended way to execute any Gradle build is with the help of the Gradle Wrapper (in short just “Wrapper”). The Wrapper is a script that invokes a declared version of Gradle, downloading it beforehand if necessary. As a result, developers can get up and running with a Gradle project quickly without having to follow manual installation processes saving your company time and money.

We should update the gradle-intro guide to use gradlew, and perhaps make a quick mention about how it works, but overall we can remove the section about installing gradle.

**Comment by Ahmad-Ayyoub** [comment]
Something like that: `./gradlew <commands>` rather than `gradle build -i` (after installation)

**Comment by julicjung** [comment]
Would love to see Gradle Wrapper be used consistently in the guide.
