### ISSUE TITLE
contextRoot is not effective in server.xml when run gradle libertyDev

### ISSUE THREAD

**Issue by Jriver19** [OpenLiberty/guide-gradle-intro#97]
when the following configuration was set in server.xml    
`<webApplication contextRoot="myapp" location="helloworld.war" />`

the default generated install_apps_configuration_1491924271.xml was
```
<?xml version="1.0" encoding="UTF-8"?>
<server>
    <webApplication id="helloworld" location="helloworld.war" name="helloworld" />
</server>
```
the contextRoot does not take effective

**Comment by gkwan-ibm** [comment]
hi @Jriver19 

is this issue related to this guide? Or you have issue for Open Liberty?
In your description, the server.xml context does not seem from https://github.com/OpenLiberty/guide-gradle-intro/blob/prod/finish/src/main/liberty/config/server.xml

**Comment by gkwan-ibm** [comment]
close this issue because didn't get more information
